spring:
  application:
    name: Welcome_Api
  boot:
    admin:
      client:
        url: http://localhost:8081/


server:
  port: 8082

management:
  endpoints:
    web:
      exposure:
        include: '*'

